[connections.snowflake]
account = "PHNBHSZ-CDB34606"
user = "DEEPAKKUMAR"
authenticator = "externalbrowser"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
